
#####################
#       Server      #
#####################
server:
    # port: 8085
    port: 80
    servlet:
        context-path: /news

#####################
#     Deployment    #
#####################

#####################
#       Spring      #
#####################

#####################
#       Database    #
#####################

spring:
    application:
        name: news
    datasource:
        platform: postgres
        url: jdbc:postgresql://fynzie.com:5432/news
        # url: jdbc:postgresql://localhost:5432/news
        username: app
        password: azerty1234!
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false

#####################
#       Actuator    #
#####################

#####################
#       Logging     #
#####################

logging:
    level:
        root: INFO
        org:
            springframework:
                web: INFO
            hibernate: INFO

eureka:  
  client:
    serviceUrl:
        # defaultZone: http://localhost:90/eureka/
        defaultZone: http://pm-eureka:80/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true