# server:
#   port: 80
# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false

server:
    port: 80

#####################
#       Actuator    #
#####################

# 1.5.x configuration
endpoints:
    cors:
        allowed-origins: '*'
        allowed-methods: 'OPTIONS, GET, POST'
        allowed-headers: '*'

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false