server:  
  port: 80

spring:  
  application:
    name: demo

eureka:  
  client:
    serviceUrl:
      defaultZone: http://pm-eureka:80/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true