server:  
  port: 80

spring:  
  application:
    name: resources

#####################
#       Actuator    #
#####################

# 1.5.x configuration
endpoints:
    cors:
        allowed-origins: '*'
        allowed-methods: 'OPTIONS, GET, POST'
        allowed-headers: '*'

eureka:  
  client:
    serviceUrl:
      # defaultZone: http://localhost:90/eureka/
      defaultZone: http://pm-eureka:80/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true