server:
  port: 80

spring:
  application:
    name: gateway

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    # ALLOW ANONYMOUS
    news:
      path: /news/**
      url: http://pm-news:80/news
    ressources:
      path: /ressources/**
      url: http://pm-ressources:80/ressources
    auth:
      path: /auth/**
      url: http://pm-accounts:80/auth
    # ROLE USER
    monsters:
      path: /monsters/**
      url: http://pm-monsters:80/monsters
    trading:
      path: /trading/**
      url: http://pm-trading:80/trading
    marketplace:
      path: /messaging/**
      url: http://pm-messages:80/marketplace
    map:
      path: /messaging/**
      url: http://pm-messages:80/map
    messaging:
      path: /messaging/**
      url: http://pm-messages:80/messaging
    # ROLE ADMIN
    admin:
      path: /admin/**
      url: http://pm-admin:80/admin
  

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry:  true
    service-url:
      default-zones: ${EUREKA_URI:http://localhost:8761/eureka}

security:
  oauth2:
    resource:
      jwt:
        key-value: 123