server:
  port: 80

spring:
  application:
    name: gateway

#####################
#       Actuator    #
#####################

# 1.5.x configuration
endpoints:
    cors:
        allowed-origins: '*'
        allowed-methods: 'OPTIONS, GET, POST'
        allowed-headers: '*'

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    # ALLOW ANONYMOUS
    news:
      path: /news/**
      serviceId: news
      strip-prefix: true
    #   url: http://pm-news:80/news
    ressources:
      path: /ressources/**
      serviceId: resources
      strip-prefix: true
    #   url: http://pm-ressources:80/ressources
    auth:
      path: /auth/**
      serviceId: accounts
      strip-prefix: true
    #   url: http://pm-accounts:80/auth
    # ROLE USER
    monsters:
      path: /monsters/**
      serviceId: monsters
      strip-prefix: true
    #   url: http://pm-monsters:80/monsters
    trading:
      path: /trading/**
      serviceId: trading
      strip-prefix: true
    #   url: http://pm-trading:80/trading
    marketplace:
      path: /messaging/**
      serviceId: marketplace
      strip-prefix: true
    #   url: http://pm-messages:80/marketplace
    map:
      path: /messaging/**
      serviceId: map
      strip-prefix: true
    #   url: http://pm-messages:80/map
    messaging:
      path: /messaging/**
      serviceId: messaging
      strip-prefix: true
    #   url: http://pm-messages:80/messaging
    # ROLE ADMIN
    admin:
      path: /admin/**
      serviceId: admin
      strip-prefix: true
    #   url: http://pm-admin:80/admin
    service-discovery:
      path: /service-discovery/**
      url: http://pm-eureka:80
      strip-prefix: true

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://pm-eureka:80/eureka/
    registerWithEureka: false

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     register-with-eureka: true
#     fetch-registry:  true
#     service-url:
#       default-zones: ${EUREKA_URI:http://pm-eureka:80/eureka}

security:
  oauth2:
    resource:
      jwt:
        key-value: 123