INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (1, 'Aboudbra le Porteur', 'aboudbra-le-porteur', 35, 47, 2384);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (2, 'Abrakadnuzar', 'abrakadnuzar', 40, 52, 2385);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (3, 'Abrakanette l''Encapsulé', 'abrakanette-lencapsule', 78, 90, 2388);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (4, 'Abrakildas le Vénérable', 'abrakildas-le-venerable', 74, 86, 2389);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (5, 'Abrakine le Sombre', 'abrakine-le-sombre', 131, 143, 2544);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (6, 'Abraklette le Fondant', 'abraklette-le-fondant', 80, 92, 2386);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (7, 'Abrakroc l''édenté', 'abrakroc-ledente', 38, 50, 2309);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (8, 'Abrinos le Clair', 'abrinos-le-clair', 150, 162, 2381);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (9, 'Ameur la Laide', 'ameur-la-laide', 35, 47, 2391);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (10, 'Arabord la Cruche', 'arabord-la-cruche', 40, 48, 2311);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (11, 'Arachitik la Souffreteuse', 'arachitik-la-souffreteuse', 11, 15, 2312);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (12, 'Araknay la Galopante', 'araknay-la-galopante', 22, 30, 2393);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (13, 'Arakozette l''Intrépide', 'arakozette-lintrepide', 35, 43, 2392);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (14, 'Arakule la Revancharde', 'arakule-la-revancharde', 16, 20, 2310);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (15, 'Bambono le Divin', 'bambono-le-divin', 77, 97, 2398);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (16, 'Bambouské le Camouflé', 'bambouske-le-camoufle', 36, 44, 2548);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (17, 'Bandapar l''Exclu', 'bandapar-lexclu', 42, 50, 2313);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (18, 'Bandson le Tonitruant', 'bandson-le-tonitruant', 37, 49, 2314);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (19, 'Barchwork le Multicolore', 'barchwork-le-multicolore', 37, 49, 2417);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (20, 'Barebourd le Comte', 'barebourd-le-comte', 58, 70, 2545);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (21, 'Bi le Partageur', 'bi-le-partageur', 24, 28, 2400);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (22, 'Bilvoezé le Bonimenteur', 'bilvoeze-le-bonimenteur', 24, 28, 2399);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (23, 'Bistou le Quêteur', 'bistou-le-queteur', 24, 28, 2396);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (24, 'Bistou le Rieur', 'bistou-le-rieur', 24, 28, 2401);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (25, 'Bitoven le Musicien', 'bitoven-le-musicien', 130, 142, 2546);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (26, 'Blof l''Apathique', 'blof-lapathique', 52, 60, 2407);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (27, 'Bloporte le Veule', 'bloporte-le-veule', 52, 60, 2406);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (28, 'Blordur l''Infect', 'blordur-linfect', 52, 60, 2405);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (29, 'Blorie L''assourdissante', 'blorie-lassourdissante', 52, 60, 2404);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (30, 'Boombata le Garde', 'boombata-le-garde', 82, 90, 2408);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (31, 'Boostif l''Affamé', 'boostif-laffame', 25, 29, 2549);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (32, 'Boudalf le Blanc', 'boudalf-le-blanc', 22, 30, 2315);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (33, 'Boudur le Raide', 'boudur-le-raide', 35, 47, 2318);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (34, 'Boufdégou le Refoulant', 'boufdegou-le-refoulant', 22, 30, 2317);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (35, 'Bouflet le Puéril', 'bouflet-le-pueril', 22, 30, 2324);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (36, 'Boulgourvil le Lointain', 'boulgourvil-le-lointain', 22, 30, 2316);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (37, 'Bouliver le Géant', 'bouliver-le-geant', 95, 107, 2363);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (38, 'Bramin le Bicéphale', 'bramin-le-bicephale', 65, 85, 2412);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (39, 'Brouste l''Humiliant', 'brouste-lhumiliant', 127, 139, 2550);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (40, 'Buldeflore le Pénétrant', 'buldeflore-le-penetrant', 38, 46, 2413);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (41, 'Bulgig le Danseur', 'bulgig-le-danseur', 75, 83, 2414);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (42, 'Bulleur le Dormeur', 'bulleur-le-dormeur', 35, 43, 2411);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (43, 'Bulsavon le Gonflé', 'bulsavon-le-gonfle', 49, 57, 2415);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (44, 'Bworkasse le Dégoutant', 'bworkasse-le-degoutant', 44, 56, 2416);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (45, 'Bwormage le Respectueux', 'bwormage-le-respectueux', 39, 51, 2418);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (46, 'Caboume l''Artilleur', 'caboume-lartilleur', 82, 90, 2419);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (47, 'Cavordemal le Sorcier', 'cavordemal-le-sorcier', 42, 50, 2420);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (48, 'Chafalfer l''Optimiste', 'chafalfer-loptimiste', 25, 37, 2321);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (49, 'Chafemal le Bagarreur', 'chafemal-le-bagarreur', 32, 40, 2319);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (50, 'Chaffoin le Sournois', 'chaffoin-le-sournois', 33, 41, 2421);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (51, 'Chafmarcel le Fêtard', 'chafmarcel-le-fetard', 42, 50, 2320);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (52, 'Chafrit le Barbare', 'chafrit-le-barbare', 42, 50, 2422);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (53, 'Chalan le Commerçant', 'chalan-le-commercant', 42, 50, 2322);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (54, 'Chamchie le Difficile', 'chamchie-le-difficile', 16, 20, 2323);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (55, 'Chamdblé le Cultivé', 'chamdble-le-cultive', 35, 43, 2426);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (56, 'Chamflay le Ballonné', 'chamflay-le-ballonne', 35, 43, 2425);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (57, 'Chamilero le Malchanceux', 'chamilero-le-malchanceux', 172, 180, 2553);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (58, 'Chamitant le Dilettante', 'chamitant-le-dilettante', 52, 60, 2423);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (59, 'Chamoute le Duveteux', 'chamoute-le-duveteux', 172, 180, 2552);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (60, 'Champayr le Disjoncté', 'champayr-le-disjoncte', 35, 43, 2427);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (61, 'Champayt l''Odorant', 'champayt-lodorant', 35, 43, 2424);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (62, 'Champmé le Méchant', 'champme-le-mechant', 172, 180, 2600);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (63, 'Champolyon le Polyglotte', 'champolyon-le-polyglotte', 172, 180, 2551);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (64, 'Champoul l''Illuminé', 'champoul-lillumine', 172, 180, 2373);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (65, 'Chevaustine le Reconstruit', 'chevaustine-le-reconstruit', 27, 35, 2430);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (66, 'Chiendanlémin l''Illusionniste', 'chiendanlemin-lillusionniste', 125, 137, 2554);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (67, 'Chonstip la Passagère', 'chonstip-la-passagere', 42, 50, 2325);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (68, 'Citassaté le Service', 'citassate-le-service', 25, 45, 2431);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (69, 'Codenlgaz le Problème', 'codenlgaz-le-probleme', 35, 47, 2433);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (70, 'Cooligane le Névrosé', 'cooligane-le-nevrose', 59, 67, 2434);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (71, 'Corboyard l''Enigmatique', 'corboyard-lenigmatique', 38, 50, 2555);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (72, 'Corpat le Vampire', 'corpat-le-vampire', 102, 110, 2437);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (73, 'Crakmitaine le Faucheur', 'crakmitaine-le-faucheur', 62, 70, 2436);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (74, 'Cramikaz le Suicidaire', 'cramikaz-le-suicidaire', 62, 70, 2438);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (75, 'Craquetou le Fissuré', 'craquetou-le-fissure', 93, 105, 2556);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (76, 'Craquetuss le Piquant', 'craquetuss-le-piquant', 62, 70, 2326);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (77, 'Craraboss le Féérique', 'craraboss-le-feerique', 42, 50, 2327);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (78, 'Crathdogue le Cruel', 'crathdogue-le-cruel', 96, 108, 2561);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (79, 'Crognan le Barbare', 'crognan-le-barbare', 62, 70, 2440);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (80, 'Crok le Beau', 'crok-le-beau', 61, 77, 2428);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (81, 'Crolnareff l''Exilé', 'crolnareff-lexile', 42, 50, 2439);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (82, 'Cromikay le Néophyte', 'cromikay-le-neophyte', 62, 70, 2378);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (83, 'Cruskof le Rustre', 'cruskof-le-rustre', 36, 48, 2559);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (84, 'Crusmeyer le Pervers', 'crusmeyer-le-pervers', 36, 48, 2560);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (85, 'Crustensyl le Pragmatique', 'crustensyl-le-pragmatique', 36, 48, 2558);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (86, 'Crustterus l''Organique', 'crustterus-lorganique', 36, 48, 2557);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (87, 'Diskord le Belliqueux', 'diskord-le-belliqueux', 114, 126, 2562);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (88, 'Doktopuss le Maléfique', 'doktopuss-le-malefique', 70, 78, 2442);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (89, 'Don Kizoth l''Obstiné', 'don-kizoth-lobstine', 126, 138, 2578);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (90, 'Dragalgan l''Effervescent', 'dragalgan-leffervescent', 84, 108, 2455);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (91, 'Dragdikal le Décisif', 'dragdikal-le-decisif', 100, 120, 2464);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (92, 'Drageaufol la Joyeuse', 'drageaufol-la-joyeuse', 110, 122, 2460);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (93, 'Dragioli le Succulent', 'dragioli-le-succulent', 84, 108, 2459);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (94, 'Dragkouine la Déguisée', 'dragkouine-la-deguisee', 60, 68, 2450);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (95, 'Draglida la Disparue', 'draglida-la-disparue', 55, 67, 2379);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (96, 'Dragma le Bouillant', 'dragma-le-bouillant', 70, 78, 2446);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (97, 'Dragminster le Magicien', 'dragminster-le-magicien', 110, 122, 2454);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (98, 'Dragmoclaiss le Fataliste', 'dragmoclaiss-le-fataliste', 60, 68, 2372);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (99, 'Dragnostik le Sceptique', 'dragnostik-le-sceptique', 60, 68, 2449);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (100, 'Dragnoute l''Irascible', 'dragnoute-lirascible', 60, 72, 2465);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (101, 'Dragobert le Monarque', 'dragobert-le-monarque', 100, 120, 2452);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (102, 'Dragoeth le Penseur', 'dragoeth-le-penseur', 70, 78, 2445);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (103, 'Dragonienne l''Econome', 'dragonienne-leconome', 102, 118, 2461);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (104, 'Dragoo le Cramoisi', 'dragoo-le-cramoisi', 70, 78, 2448);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (105, 'Dragsta le Détendu', 'dragsta-le-detendu', 50, 58, 2451);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (106, 'Dragstayr le Fonceur', 'dragstayr-le-fonceur', 60, 68, 2377);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (107, 'Dragstik le Frustre', 'dragstik-le-frustre', 50, 58, 2369);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (108, 'Dragstore le Généraliste', 'dragstore-le-generaliste', 50, 58, 2367);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (109, 'Dragtarus le Bellâtre', 'dragtarus-le-bellatre', 110, 122, 2456);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (110, 'Dragtonien le Malvoyant', 'dragtonien-le-malvoyant', 70, 78, 2447);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (111, 'Dragtopaile l''Excavateur', 'dragtopaile-lexcavateur', 84, 108, 2453);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (112, 'Dragtula l''Ancien', 'dragtula-lancien', 50, 58, 2368);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (113, 'Dragybuss le Sucré', 'dragybuss-le-sucre', 84, 108, 2457);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (114, 'Drakolage le Tentateur', 'drakolage-le-tentateur', 90, 98, 2462);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (115, 'Draquetteur le Voleur', 'draquetteur-le-voleur', 110, 122, 2458);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (116, 'Ecorfé la Vive', 'ecorfe-la-vive', 128, 140, 2360);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (117, 'Fanburn le Viril', 'fanburn-le-viril', 400, 440, 2477);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (118, 'Fandanleuil le Précis', 'fandanleuil-le-precis', 42, 50, 2467);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (119, 'Fandouich l''Hautain', 'fandouich-lhautain', 170, 210, 2471);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (120, 'Fanfancisco le Cosmopolite', 'fanfancisco-le-cosmopolite', 60, 80, 2474);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (121, 'Fanhnatur le Simple', 'fanhnatur-le-simple', 60, 80, 2473);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (122, 'Fanhopruno le Gourmet', 'fanhopruno-le-gourmet', 220, 220, 2374);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (123, 'Fanjipann le Sucré', 'fanjipann-le-sucre', 60, 80, 2476);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (124, 'Fanjo le Pilote', 'fanjo-le-pilote', 60, 80, 2475);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (125, 'Fanlabiz le Véloce', 'fanlabiz-le-veloce', 42, 50, 2466);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (126, 'Fanlagoel le Comique', 'fanlagoel-le-comique', 230, 250, 2564);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (127, 'Fanlmyl l''Acuité', 'fanlmyl-lacuite', 60, 80, 2472);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (128, 'Fansiss la Brêle', 'fansiss-la-brele', 380, 400, 2470);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (129, 'Fansissla l''Âne', 'fansissla-lane', 160, 180, 2370);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (130, 'Fanstatik l''Etonnant', 'fanstatik-letonnant', 164, 180, 2469);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (131, 'Fantassein le Soldat', 'fantassein-le-soldat', 230, 270, 2483);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (132, 'Fantoch le Pantin', 'fantoch-le-pantin', 42, 50, 2563);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (133, 'Fantrask le Rêveur', 'fantrask-le-reveur', 42, 50, 2468);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (134, 'Farlon l''Enfant', 'farlon-lenfant', 90, 98, 2432);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (135, 'Faufoll la Joyeuse', 'faufoll-la-joyeuse', 108, 120, 2567);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (136, 'Floanna la Blonde', 'floanna-la-blonde', 129, 141, 2565);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (137, 'Forboyar l''Enigmatique', 'forboyar-lenigmatique', 41, 53, 2328);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (138, 'Fossamoel le Juteux', 'fossamoel-le-juteux', 100, 112, 2482);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (139, 'Fourapin le Chaud', 'fourapin-le-chaud', 92, 100, 2484);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (140, 'Garsim le Mort', 'garsim-le-mort', 32, 40, 2486);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (141, 'Gastroth la Contagieuse', 'gastroth-la-contagieuse', 117, 129, 2566);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (142, 'Gelanal le Huileux', 'gelanal-le-huileux', 46, 62, 2487);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (143, 'Gelaviv le Glaçon', 'gelaviv-le-glacon', 54, 62, 2376);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (144, 'Geloliaine l''Aérien', 'geloliaine-laerien', 50, 62, 2371);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (145, 'Germinol l''Indigent', 'germinol-lindigent', 120, 128, 2568);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (146, 'Ginsenk le Stimulant', 'ginsenk-le-stimulant', 35, 47, 2493);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (147, 'Gloubibou le Gars', 'gloubibou-le-gars', 92, 100, 2495);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (148, 'Gobstiniais le Têtu', 'gobstiniais-le-tetu', 20, 24, 2494);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (149, 'Grandilok le Clameur', 'grandilok-le-clameur', 52, 60, 2498);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (150, 'Guerrite le Veilleur', 'guerrite-le-veilleur', 100, 112, 2497);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (151, 'Guerumoth le Collant', 'guerumoth-le-collant', 120, 132, 2569);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (152, 'Kanasukr le Mielleux', 'kanasukr-le-mielleux', 62, 70, 2503);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (153, 'Kannémik le Maigre', 'kannemik-le-maigre', 52, 60, 2505);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (154, 'Kannibal le Lecteur', 'kannibal-le-lecteur', 52, 60, 2502);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (155, 'Kannisterik le Forcené', 'kannisterik-le-forcene', 52, 60, 2506);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (156, 'Kapota la Fraise', 'kapota-la-fraise', 52, 60, 2507);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (157, 'Kaskapointhe la Couverte', 'kaskapointhe-la-couverte', 146, 162, 2570);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (158, 'Kido l''Âtre', 'kido-latre', 95, 107, 2571);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (159, 'Kilimanj''haro le Grimpeur', 'kilimanjharo-le-grimpeur', 98, 110, 2572);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (160, 'Kiroyal le Sirupeux', 'kiroyal-le-sirupeux', 35, 47, 2508);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (161, 'Kitsoudbra le Malodorant', 'kitsoudbra-le-malodorant', 71, 79, 2510);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (162, 'Kitsoufre l''Explosif', 'kitsoufre-lexplosif', 75, 83, 2512);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (163, 'Kitsoupierre le Récipient', 'kitsoupierre-le-recipient', 69, 77, 2329);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (164, 'Kitsoupopulère le Généreux', 'kitsoupopulere-le-genereux', 73, 81, 2511);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (165, 'Koakofrui le Confit', 'koakofrui-le-confit', 80, 88, 2516);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (166, 'Koalaboi le Calorifère', 'koalaboi-le-calorifere', 104, 116, 2514);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (167, 'Koalastrof la Naturelle', 'koalastrof-la-naturelle', 60, 68, 2517);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (168, 'Koalvissie le Chauve', 'koalvissie-le-chauve', 102, 114, 2519);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (169, 'Koamaembair le Coulant', 'koamaembair-le-coulant', 80, 88, 2513);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (170, 'Koamag''oel le Défiguré', 'koamagoel-le-defigure', 102, 114, 2429);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (171, 'Koarmit la Batracienne', 'koarmit-la-batracienne', 80, 88, 2518);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (172, 'Koaskette la Chapelière', 'koaskette-la-chapeliere', 80, 88, 2509);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (173, 'Koasossyal le Psychopathe', 'koasossyal-le-psychopathe', 80, 88, 2515);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (174, 'Koktèle le Secoué', 'koktele-le-secoue', 42, 50, 2573);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (175, 'Kolforthe l''Indécollable', 'kolforthe-lindecollable', 62, 70, 2520);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (176, 'Krapahut le Randonneur', 'krapahut-le-randonneur', 110, 118, 2521);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (177, 'Kwoanneur le Frimeur', 'kwoanneur-le-frimeur', 32, 40, 2522);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (178, 'Larchimaide la Poussée', 'larchimaide-la-poussee', 16, 20, 2332);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (179, 'Larvapstrè le Subjectif', 'larvapstre-le-subjectif', 16, 20, 2331);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (180, 'Larvomatik le Propre', 'larvomatik-le-propre', 16, 20, 2339);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (181, 'Larvonika l''Instrument', 'larvonika-linstrument', 16, 20, 2574);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (182, 'Léopolnor le Barde', 'leopolnor-le-barde', 125, 137, 2527);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (183, 'Let le Rond', 'let-le-rond', 35, 47, 2525);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (184, 'Mahoku le Botté', 'mahoku-le-botte', 127, 139, 2526);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (185, 'Maître Amboat le Moqueur', 'maitre-amboat-le-moqueur', 37, 49, 2532);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (186, 'Maître Koantik le Théoricien', 'maitre-koantik-le-theoricien', 108, 120, 2531);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (187, 'Maître Onom le Régulier', 'maitre-onom-le-regulier', 62, 70, 2359);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (188, 'Mamakomou l''Âge', 'mamakomou-lage', 90, 98, 2528);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (189, 'Mandalo l''Aqueuse', 'mandalo-laqueuse', 100, 108, 2529);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (190, 'Meuroup le Prêtre', 'meuroup-le-pretre', 143, 155, 2577);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (191, 'Milipatte la Griffe', 'milipatte-la-griffe', 22, 30, 2333);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (192, 'Milipussien le Géant', 'milipussien-le-geant', 22, 30, 2334);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (193, 'Minoskour le Sauveur', 'minoskour-le-sauveur', 100, 108, 2533);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (194, 'Minsinistre l''Elu', 'minsinistre-lelu', 39, 51, 2335);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (195, 'Momikonos la Bandelette', 'momikonos-la-bandelette', 106, 118, 2534);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (196, 'Mosketère le Dévoué', 'mosketere-le-devoue', 16, 20, 2336);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (197, 'Mufguedin le Suprême', 'mufguedin-le-supreme', 94, 106, 2580);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (198, 'Muloufok l''Hilarant', 'muloufok-lhilarant', 92, 100, 2337);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (199, 'Nakuneuye le Borgne', 'nakuneuye-le-borgne', 82, 90, 2538);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (200, 'Nelvin le Boulet', 'nelvin-le-boulet', 35, 47, 2539);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (201, 'Nerdeubeu le Flagellant', 'nerdeubeu-le-flagellant', 126, 138, 2579);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (202, 'Neufedur le Flottant', 'neufedur-le-flottant', 20, 24, 2542);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (203, 'Nipulnislip l''Exhibitionniste', 'nipulnislip-lexhibitionniste', 35, 47, 2540);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (204, 'Nodkoku le Trahi', 'nodkoku-le-trahi', 42, 50, 2541);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (205, 'Onihylis le Destructeur', 'onihylis-le-destructeur', 75, 75, 2543);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (206, 'Osuxion le Vampirique', 'osuxion-le-vampirique', 35, 47, 2585);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (207, 'Ouashouash l''Exubérant', 'ouashouash-lexuberant', 92, 104, 2575);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (208, 'Ouassébo l''Esthète', 'ouassebo-lesthete', 32, 40, 2524);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (209, 'Ouature la Mobile', 'ouature-la-mobile', 32, 40, 2616);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (210, 'Ougaould le Parasite', 'ougaould-le-parasite', 42, 50, 2589);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (211, 'Palmbytch la Bronzée', 'palmbytch-la-bronzee', 37, 49, 2581);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (212, 'Palmiche le Serein', 'palmiche-le-serein', 37, 49, 2583);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (213, 'Palmiflette le Convivial', 'palmiflette-le-convivial', 37, 49, 2584);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (214, 'Palmito le Menteur', 'palmito-le-menteur', 37, 49, 2582);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (215, 'Pandanlagl la Saoule', 'pandanlagl-la-saoule', 46, 70, 2590);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (216, 'Pandimaensh l''Animateur', 'pandimaensh-lanimateur', 39, 51, 2592);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (217, 'Pandimy le Contagieux', 'pandimy-le-contagieux', 40, 52, 2593);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (218, 'Pandive le Végétarien', 'pandive-le-vegetarien', 200, 240, 2597);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (219, 'Pandouille le Titubant', 'pandouille-le-titubant', 56, 80, 2591);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (220, 'Pangraive le Militant', 'pangraive-le-militant', 50, 90, 2598);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (221, 'Pékeutar le Tireur', 'pekeutar-le-tireur', 80, 88, 2271);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (222, 'Pichakoté le Dégoutant', 'pichakote-le-degoutant', 16, 20, 2272);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (223, 'Pichdourse le Puissant', 'pichdourse-le-puissant', 16, 20, 2338);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (224, 'Pichduitre le Totem', 'pichduitre-le-totem', 16, 20, 2346);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (225, 'Pichtoire l''Erudit', 'pichtoire-lerudit', 16, 20, 2340);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (226, 'Pioufe la Maquillée', 'pioufe-la-maquillee', 11, 15, 2343);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (227, 'Pioukas la Plante', 'pioukas-la-plante', 11, 15, 2345);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (228, 'Pioulbrineur le Mercenaire', 'pioulbrineur-le-mercenaire', 11, 15, 2342);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (229, 'Pioulette la Coquine', 'pioulette-la-coquine', 11, 15, 2344);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (230, 'Pioussokrim le Délétère', 'pioussokrim-le-deletere', 11, 15, 2347);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (231, 'Pioustone le Problème', 'pioustone-le-probleme', 11, 15, 2341);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (232, 'Piradain le Pingre', 'piradain-le-pingre', 80, 88, 2270);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (233, 'Pissdane l''Insipide', 'pissdane-linsipide', 16, 20, 2348);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (234, 'Poolopo la Traditionnelle', 'poolopo-la-traditionnelle', 142, 158, 2383);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (235, 'Porfavor le Quémandeur', 'porfavor-le-quemandeur', 42, 50, 2397);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (236, 'Preskapwal le Tendancieux', 'preskapwal-le-tendancieux', 22, 30, 2349);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (237, 'Radoutable le Craint', 'radoutable-le-craint', 22, 30, 2350);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (238, 'Ratéhaifaim le Professeur', 'ratehaifaim-le-professeur', 52, 60, 2275);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (239, 'Ratlbol l''Aigri', 'ratlbol-laigri', 52, 60, 2273);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (240, 'Rauligo le Sale', 'rauligo-le-sale', 42, 50, 2351);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (241, 'Ribibi le Cher', 'ribibi-le-cher', 34, 42, 2276);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (242, 'Rostensyl la Cuisinière', 'rostensyl-la-cuisiniere', 19, 27, 2277);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (243, 'Roy le Merlin', 'roy-le-merlin', 192, 200, 2614);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (244, 'Roz la Magicienne', 'roz-la-magicienne', 16, 20, 2352);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (245, 'Sampi l''Eternel', 'sampi-leternel', 40, 48, 2279);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (246, 'Sangria le Fruité', 'sangria-le-fruite', 22, 30, 2353);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (247, 'Scapé l''Epée', 'scape-lepee', 34, 42, 2280);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (248, 'Scaramel le Fondant', 'scaramel-le-fondant', 34, 42, 2283);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (249, 'Scaratyn l''Huître', 'scaratyn-lhuitre', 110, 118, 2615);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (250, 'Scarfayss le Balafré', 'scarfayss-le-balafre', 34, 42, 2281);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (251, 'Scarouarze l''Epopée', 'scarouarze-lepopee', 34, 42, 2282);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (252, 'Scorpitène l''Enflammé', 'scorpitene-lenflamme', 62, 70, 2285);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (253, 'Seripoth l''Ennemi', 'seripoth-lennemi', 123, 135, 2587);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (254, 'Serpistol l''Illustre', 'serpistol-lillustre', 52, 60, 2286);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (255, 'Serpistule le Purulent', 'serpistule-le-purulent', 120, 128, 2287);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (256, 'Soryonara le Poli', 'soryonara-le-poli', 126, 138, 2278);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (257, 'Sourizoto le Collant', 'sourizoto-le-collant', 1, 1, 2354);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (258, 'Sparoket le Lanceur', 'sparoket-le-lanceur', 57, 69, 2588);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (259, 'Susbewl l''Hypocrite', 'susbewl-lhypocrite', 35, 47, 2289);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (260, 'Tikosto le Mousse', 'tikosto-le-mousse', 42, 50, 2292);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (261, 'Tiwalpé le Dévêtu', 'tiwalpe-le-devetu', 41, 49, 2293);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (262, 'Tiwa''Missou le Gateux', 'tiwamissou-le-gateux', 42, 50, 2402);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (263, 'Tiwoflan le Lâche', 'tiwoflan-le-lache', 40, 48, 2294);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (264, 'Tofuldebeu l''Explosif', 'tofuldebeu-lexplosif', 32, 40, 2355);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (265, 'Tofumanchou l''Empereur', 'tofumanchou-lempereur', 32, 40, 2357);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (266, 'Tofurapin le Pétri', 'tofurapin-le-petri', 11, 15, 2356);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (267, 'Tortenssia la Fleurie', 'tortenssia-la-fleurie', 42, 50, 2295);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (268, 'Torthur la Lutte', 'torthur-la-lutte', 42, 50, 2298);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (269, 'Tortilleur le Coulé', 'tortilleur-le-coule', 42, 50, 2296);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (270, 'Tortorak le Cornu', 'tortorak-le-cornu', 42, 50, 2297);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (271, 'Toufou le Benêt', 'toufou-le-benet', 97, 109, 2547);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (272, 'Tourbiket le Virevoletant', 'tourbiket-le-virevoletant', 100, 112, 2361);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (273, 'Tour le Vice', 'tour-le-vice', 16, 20, 2358);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (274, 'Toutouf le Velu', 'toutouf-le-velu', 144, 160, 2382);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (275, 'Tromplamor le Survivant', 'tromplamor-le-survivant', 172, 180, 2601);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (276, 'Tronkoneuz la Tranchante', 'tronkoneuz-la-tranchante', 33, 45, 2299);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (277, 'Trooyé l''Oxydé', 'trooye-loxyde', 112, 120, 2300);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (278, 'Trukul le Lent', 'trukul-le-lent', 92, 100, 2301);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (279, 'Vampunor le Glacial', 'vampunor-le-glacial', 32, 40, 2302);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (280, 'Wabbitud le Constant', 'wabbitud-le-constant', 44, 52, 2304);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (281, 'Wagnagnah le Sanglant', 'wagnagnah-le-sanglant', 46, 54, 2403);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (282, 'Wara l''Amer', 'wara-lamer', 106, 118, 2307);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (283, 'Warkolad l''Etreinte', 'warkolad-letreinte', 74, 82, 2306);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (284, 'Watdogue le Bien Nommé', 'watdogue-le-bien-nomme', 48, 56, 2305);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (285, 'Wokènrôl le Danseur', 'wokenrol-le-danseur', 52, 60, 2308);
INSERT INTO public.t_monsters (id, name, slug, min_level, max_level, ankama_id) VALUES (286, 'YokaiKoral le Duel', 'yokaikoral-le-duel', 128, 140, 2303);