version: "3.5"
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "accounts"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "azerty1234"
    ports:
      - "5532:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #volumes:
      #- elasticsearch-volume

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    container_name: kibana
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    #volumes:
      #- kibana-volume

  gateway:
    image: pocket_monsters-gateway:latest
    container_name: pm-gateway
    ports:
      - 80:80

  accounts:
    image: pocket_monsters-accounts:latest
    container_name: pm-accounts
    ports:
      - 81:80

  monsters:
    image: pocket_monsters-monsters:latest
    container_name: pm-monsters
    ports:
      - 82:80
      
  # trading

  # messaging

  # news

  ressources:
    image: pocket_monsters-ressources:latest
    container_name: pm-ressources
    ports:
      - 89:80

  eureka:
    image: pocket_monsters-eureka:latest
    container_name: pm-eureka
    ports:
      - 90:80

volumes:
  postgres-volume:
    external: true