################################################################
#                       NOT USED FILE                          #
################################################################

version: "3.5"
services:

  # gateway
  gateway:
    image: pocket_monsters-gateway:latest
    container_name: pm-gateway
    ports:
      - 8080:80

  accounts:
    image: pocket_monsters-accounts:latest
    container_name: pm-accounts
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8081:80

  monsters:
    image: pocket_monsters-monsters:latest
    container_name: pm-monsters
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8082:80
      
  # trading
  trading:
    image: pocket_monsters-trading:latest
    container_name: pm-trading
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8083:80

  # messaging

  # news
  ressources:
    image: pocket_monsters-ressources:latest
    container_name: pm-news
    ports:
      - 8088:80

  ressources:
    image: pocket_monsters-ressources:latest
    container_name: pm-ressources
    ports:
      - 8089:80

  eureka:
    image: pocket_monsters-eureka:latest
    container_name: pm-eureka
    ports:
      - 8090:80

networks:
  default:
    external:
      name: default_network