version: "3.5"
services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --admin-password '$$2y$$05$$IBiI1bppDZtI4FZJz/GJv.qQhqotS64ZbWHqXVHN7woW3SzpmpMHy'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-volume:/data
    ports:
      - "9000:9000"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: accounts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: azerty1234
    ports:
      - "5432:5432"
    volumes:
      #- ../../data/postgres:/var/lib/postgresql/data
      - postgres-volume:/var/lib/postgresql/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      # - xpack.security.enabled=false
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    container_name: kibana
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    volumes:
      - kibana-volume
    depends_on:
      - elasticsearch
    restart: unless-stopped

  messagebus:
    image: rabbitmq:3.6-management
    container_name: pm-messagebus
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{error}]"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: azerty1234
    ports:
      - "5772:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  portainer-volume:
    external: true
  postgres-volume:
    external: true
  elasticsearch-volume:
    external: true
  kibana-volume:
    external: true

networks:
  default:
    external:
      name: default_network