version: "3.5"
services:

  gateway:
    image: pocket_monsters-gateway:latest
    container_name: pm-gateway
    ports:
      - 80:80

  accounts:
    image: pocket_monsters-accounts:latest
    container_name: pm-accounts
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 81:80

  monsters:
    image: pocket_monsters-monsters:latest
    container_name: pm-monsters
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 82:80
      
  # trading
  trading:
    image: pocket_monsters-trading:latest
    container_name: pm-trading
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 83:80

  # messaging

  # news

  ressources:
    image: pocket_monsters-ressources:latest
    container_name: pm-ressources
    ports:
      - 89:80

  eureka:
    image: pocket_monsters-eureka:latest
    container_name: pm-eureka
    ports:
      - 90:80

networks:
  default:
    external:
      name: default_network